import { MigrationInterface, QueryRunner } from "typeorm";

export class UsersRolesPermitions1715837914968 implements MigrationInterface {
    name = 'UsersRolesPermitions1715837914968'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "ROL_ROLES" ("ROL_CODIGO" SERIAL NOT NULL, "ROL_ROL" character varying(50) NOT NULL, "ROL_DESCRIPCION" character varying(500), CONSTRAINT "PK_990c7011f28f5cee167bab59e03" PRIMARY KEY ("ROL_CODIGO")); COMMENT ON COLUMN "ROL_ROLES"."ROL_CODIGO" IS 'Clave primaria de tabla'; COMMENT ON COLUMN "ROL_ROLES"."ROL_ROL" IS 'Nombre del rol'; COMMENT ON COLUMN "ROL_ROLES"."ROL_DESCRIPCION" IS 'Descripción del rol'`);
        await queryRunner.query(`CREATE TABLE "PAS_PERMISOS_ASIGNADOS" ("PAS_CODIGO" SERIAL NOT NULL, "PAS_USUARIO_CREACION" character varying(30) NOT NULL, "PAS_FECHA_CREACION" TIMESTAMP, "FK_ROL" integer, "FK_USUARIO" integer, CONSTRAINT "PK_c8fcfa9caf474dc56d6e2dedace" PRIMARY KEY ("PAS_CODIGO")); COMMENT ON COLUMN "PAS_PERMISOS_ASIGNADOS"."PAS_CODIGO" IS 'Clave primaria de tabla'; COMMENT ON COLUMN "PAS_PERMISOS_ASIGNADOS"."PAS_USUARIO_CREACION" IS 'Documento de usuario que creó'; COMMENT ON COLUMN "PAS_PERMISOS_ASIGNADOS"."PAS_FECHA_CREACION" IS 'Fecha creación'; COMMENT ON COLUMN "PAS_PERMISOS_ASIGNADOS"."FK_ROL" IS 'Clave primaria de tabla'; COMMENT ON COLUMN "PAS_PERMISOS_ASIGNADOS"."FK_USUARIO" IS 'Clave primaria de tabla'`);
        await queryRunner.query(`CREATE TABLE "USU_USUARIO" ("USU_CODIGO" SERIAL NOT NULL, "USU_USUARIO" character varying(50) NOT NULL, "USU_PASSWORD" character varying(100) NOT NULL, "USU_ESTADO" boolean NOT NULL DEFAULT true, "USU_VALIDADO" boolean NOT NULL DEFAULT false, "USU_USUARIO_CREO" character varying(30), "USU_FECHA_CREACION" TIMESTAMP, "USU_USUARIO_ACTUALIZACION" character varying(30), "USU_FECHA_ACTUALIZACION" TIMESTAMP, "FK_PERSONA" integer, CONSTRAINT "UQ_37ef97cd744618d176376db9d93" UNIQUE ("USU_USUARIO"), CONSTRAINT "PK_1f1dc5fb38f6e6c99de610d384a" PRIMARY KEY ("USU_CODIGO")); COMMENT ON COLUMN "USU_USUARIO"."USU_CODIGO" IS 'Clave primaria de tabla'; COMMENT ON COLUMN "USU_USUARIO"."USU_USUARIO" IS 'Nickname del usuario'; COMMENT ON COLUMN "USU_USUARIO"."USU_PASSWORD" IS 'Contraseña del usuario'; COMMENT ON COLUMN "USU_USUARIO"."USU_ESTADO" IS 'Estado del usuario'; COMMENT ON COLUMN "USU_USUARIO"."USU_VALIDADO" IS 'Usuario validado'; COMMENT ON COLUMN "USU_USUARIO"."USU_USUARIO_CREO" IS 'Documento de usuario que creó'; COMMENT ON COLUMN "USU_USUARIO"."USU_FECHA_CREACION" IS 'Fecha creación'; COMMENT ON COLUMN "USU_USUARIO"."USU_USUARIO_ACTUALIZACION" IS 'Documento de usuario que actualizó'; COMMENT ON COLUMN "USU_USUARIO"."USU_FECHA_ACTUALIZACION" IS 'Fecha creación'; COMMENT ON COLUMN "USU_USUARIO"."FK_PERSONA" IS 'Clave primaria de tabla'`);
        await queryRunner.query(`ALTER TABLE "PAS_PERMISOS_ASIGNADOS" ADD CONSTRAINT "FK_1860336c5ff177e6fb0912ae676" FOREIGN KEY ("FK_ROL") REFERENCES "ROL_ROLES"("ROL_CODIGO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PAS_PERMISOS_ASIGNADOS" ADD CONSTRAINT "FK_9529a39f1acbd635b9254164e4f" FOREIGN KEY ("FK_USUARIO") REFERENCES "USU_USUARIO"("USU_CODIGO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "USU_USUARIO" ADD CONSTRAINT "FK_6473a9315dcff49ed51cd277f67" FOREIGN KEY ("FK_PERSONA") REFERENCES "PER_PERSONAS"("PER_CODIGO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "USU_USUARIO" DROP CONSTRAINT "FK_6473a9315dcff49ed51cd277f67"`);
        await queryRunner.query(`ALTER TABLE "PAS_PERMISOS_ASIGNADOS" DROP CONSTRAINT "FK_9529a39f1acbd635b9254164e4f"`);
        await queryRunner.query(`ALTER TABLE "PAS_PERMISOS_ASIGNADOS" DROP CONSTRAINT "FK_1860336c5ff177e6fb0912ae676"`);
        await queryRunner.query(`DROP TABLE "USU_USUARIO"`);
        await queryRunner.query(`DROP TABLE "PAS_PERMISOS_ASIGNADOS"`);
        await queryRunner.query(`DROP TABLE "ROL_ROLES"`);
    }

}
