import { MigrationInterface, QueryRunner } from "typeorm";

export class PersonsAndCampus1715622984002 implements MigrationInterface {
    name = 'PersonsAndCampus1715622984002'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "CAM_CAMPUS" ("PER_CODIGO" SERIAL NOT NULL, "CAM_NOMBRE" character varying(200) NOT NULL, "CAM_DIRECCION" character varying(150) NOT NULL, "CAM_TELEFONO1" character varying(100) NOT NULL, "CAM_TELEFONO2" character varying(100), "CAM_EMAIL1" character varying(150) NOT NULL, "CAM_EMAIL2" character varying(150), "CAM_DESCRIPCION" character varying(500), "PER_USUARIO_CREACION" character varying(30), "PER_FECHA_CREACION" TIMESTAMP, "PER_USUARIO_ACTUALIZACION" character varying(30), "PER_FECHA_ACTUALIZACION" TIMESTAMP, CONSTRAINT "PK_2494c87c42234a47524f4edb059" PRIMARY KEY ("PER_CODIGO")); COMMENT ON COLUMN "CAM_CAMPUS"."PER_CODIGO" IS 'Clave primaria de tabla'; COMMENT ON COLUMN "CAM_CAMPUS"."CAM_NOMBRE" IS 'Nombre de la Sede'; COMMENT ON COLUMN "CAM_CAMPUS"."CAM_DIRECCION" IS 'Dirección de la Sede'; COMMENT ON COLUMN "CAM_CAMPUS"."CAM_TELEFONO1" IS 'Teléfono 1 de la Sede'; COMMENT ON COLUMN "CAM_CAMPUS"."CAM_TELEFONO2" IS 'Teléfono 2 de la Sede'; COMMENT ON COLUMN "CAM_CAMPUS"."CAM_EMAIL1" IS 'Email 1 de la Sede'; COMMENT ON COLUMN "CAM_CAMPUS"."CAM_EMAIL2" IS 'Email 2 de la Sede'; COMMENT ON COLUMN "CAM_CAMPUS"."CAM_DESCRIPCION" IS 'Descripción adicional de la Sede'; COMMENT ON COLUMN "CAM_CAMPUS"."PER_USUARIO_CREACION" IS 'Documento de usuario que creó'; COMMENT ON COLUMN "CAM_CAMPUS"."PER_FECHA_CREACION" IS 'Fecha creación'; COMMENT ON COLUMN "CAM_CAMPUS"."PER_USUARIO_ACTUALIZACION" IS 'Documento de usuario que actualizó'; COMMENT ON COLUMN "CAM_CAMPUS"."PER_FECHA_ACTUALIZACION" IS 'Fecha actualización'`);
        await queryRunner.query(`CREATE TABLE "PER_PERSONAS" ("PER_CODIGO" SERIAL NOT NULL, "PER_TIPO_DOCUMENTO" character varying(30) NOT NULL, "PER_DOCUMENTO" character varying(50) NOT NULL, "PER_NOMBRES" character varying(100) NOT NULL, "PER_APELLIDOS" character varying(100) NOT NULL, "PER_GENERO" character varying(2) NOT NULL, "PER_DIRECCION" character varying(150), "PER_TELEFONO" character varying(60), "PER_EMAIL" character varying(150) NOT NULL, "PER_FECHA_NACIMIENTO" date, "PER_TIPO_SANGRE" character varying(5) NOT NULL, "PER_ESTADO" character varying(1) NOT NULL DEFAULT 'S', "PER_USUARIO_CREACION" character varying(30), "PER_FECHA_CREACION" TIMESTAMP, "PER_USUARIO_ACTUALIZACION" character varying(30), "PER_FECHA_ACTUALIZACION" TIMESTAMP, "FK_SEDE" integer, CONSTRAINT "UQ_0b53db117de50199a34c29f41fb" UNIQUE ("PER_DOCUMENTO"), CONSTRAINT "UQ_125046adb0fc1684e087a584654" UNIQUE ("PER_EMAIL"), CONSTRAINT "PK_b22a178879f0d4af0430a9442fd" PRIMARY KEY ("PER_CODIGO")); COMMENT ON COLUMN "PER_PERSONAS"."PER_CODIGO" IS 'Clave primaria de tabla'; COMMENT ON COLUMN "PER_PERSONAS"."PER_TIPO_DOCUMENTO" IS 'Tipo Documento de la Persona'; COMMENT ON COLUMN "PER_PERSONAS"."PER_DOCUMENTO" IS 'Documento de la Persona'; COMMENT ON COLUMN "PER_PERSONAS"."PER_NOMBRES" IS 'Nombres de la Persona'; COMMENT ON COLUMN "PER_PERSONAS"."PER_APELLIDOS" IS 'Apellidos de la Persona'; COMMENT ON COLUMN "PER_PERSONAS"."PER_GENERO" IS 'Sexualidad de la Persona'; COMMENT ON COLUMN "PER_PERSONAS"."PER_DIRECCION" IS 'Dirección Residencial de la Persona'; COMMENT ON COLUMN "PER_PERSONAS"."PER_TELEFONO" IS 'Celular de la Persona'; COMMENT ON COLUMN "PER_PERSONAS"."PER_EMAIL" IS 'Correo Electrónico de la Persona'; COMMENT ON COLUMN "PER_PERSONAS"."PER_FECHA_NACIMIENTO" IS 'Fecha Nacimiento de la Persona'; COMMENT ON COLUMN "PER_PERSONAS"."PER_TIPO_SANGRE" IS 'Tipo de Sangre'; COMMENT ON COLUMN "PER_PERSONAS"."PER_ESTADO" IS 'Estado Lógico de la Persona'; COMMENT ON COLUMN "PER_PERSONAS"."PER_USUARIO_CREACION" IS 'Documento de usuario que creó'; COMMENT ON COLUMN "PER_PERSONAS"."PER_FECHA_CREACION" IS 'Fecha creación'; COMMENT ON COLUMN "PER_PERSONAS"."PER_USUARIO_ACTUALIZACION" IS 'Documento de usuario que actualizó'; COMMENT ON COLUMN "PER_PERSONAS"."PER_FECHA_ACTUALIZACION" IS 'Fecha actualización'; COMMENT ON COLUMN "PER_PERSONAS"."FK_SEDE" IS 'Clave primaria de tabla'`);
        await queryRunner.query(`ALTER TABLE "PER_PERSONAS" ADD CONSTRAINT "FK_1e938ea2d84d0654b508f731c3e" FOREIGN KEY ("FK_SEDE") REFERENCES "CAM_CAMPUS"("PER_CODIGO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "PER_PERSONAS" DROP CONSTRAINT "FK_1e938ea2d84d0654b508f731c3e"`);
        await queryRunner.query(`DROP TABLE "PER_PERSONAS"`);
        await queryRunner.query(`DROP TABLE "CAM_CAMPUS"`);
    }

}
