import { MigrationInterface, QueryRunner } from "typeorm";

export class PosicionesPresupuestalesOrigen1718065462564 implements MigrationInterface {
    name = 'PosicionesPresupuestalesOrigen1718065462564'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN" ("PPR_CODIGO" SERIAL NOT NULL, "PPR_NUMERO" character varying(30) NOT NULL, "PPR_EJERCICIO" integer NOT NULL, "PPR_DENOMINACION" character varying(200) NOT NULL, "PPR_DESCRIPCION" character varying(500) NOT NULL, "PPR_ESTADO" boolean NOT NULL DEFAULT true, "PPR_USUARIO_CREACION" character varying(30), "PPR_FECHA_CREACION" TIMESTAMP, "PPR_USUARIO_ACTUALIZACION" character varying(30), "PPR_FECHA_ACTUALIZACION" TIMESTAMP, "FK_CENTRO_GESTOR" integer, CONSTRAINT "UQ_ce494620d49698b0ecf3a65ce9f" UNIQUE ("PPR_NUMERO"), CONSTRAINT "UQ_d0069127fb8c0af78f5a06307c2" UNIQUE ("PPR_DENOMINACION"), CONSTRAINT "UQ_ceee1e1c2f485190691271752d5" UNIQUE ("PPR_DESCRIPCION"), CONSTRAINT "PK_22c7ab6f7b1bf274a3aff42caa1" PRIMARY KEY ("PPR_CODIGO")); COMMENT ON COLUMN "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN"."PPR_CODIGO" IS 'Clave primaria de tabla'; COMMENT ON COLUMN "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN"."PPR_NUMERO" IS 'Número de posición presupuestal de origen'; COMMENT ON COLUMN "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN"."PPR_EJERCICIO" IS 'Ejercicio de aplicación de posición presupuestal de origen'; COMMENT ON COLUMN "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN"."PPR_DENOMINACION" IS 'Denominación de la posición presupuestal de origen'; COMMENT ON COLUMN "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN"."PPR_DESCRIPCION" IS 'Descripción de la posición presupuestal de origen'; COMMENT ON COLUMN "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN"."PPR_ESTADO" IS 'Estado lógico de eliminación de la posición presupuestal de origen'; COMMENT ON COLUMN "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN"."PPR_USUARIO_CREACION" IS 'Documento de usuario que creó'; COMMENT ON COLUMN "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN"."PPR_FECHA_CREACION" IS 'Fecha creación'; COMMENT ON COLUMN "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN"."PPR_USUARIO_ACTUALIZACION" IS 'Documento de usuario que actualizó'; COMMENT ON COLUMN "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN"."PPR_FECHA_ACTUALIZACION" IS 'Fecha actualización'; COMMENT ON COLUMN "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN"."FK_CENTRO_GESTOR" IS 'Clave primaria de tabla'`);
        await queryRunner.query(`ALTER TABLE "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN" ADD CONSTRAINT "FK_48238762f2dcb2d2cd294aef88a" FOREIGN KEY ("FK_CENTRO_GESTOR") REFERENCES "CEG_CENTROS_GESTORES"("CEG_CODIGO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN" DROP CONSTRAINT "FK_48238762f2dcb2d2cd294aef88a"`);
        await queryRunner.query(`DROP TABLE "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN"`);
    }

}
