import { MigrationInterface, QueryRunner } from "typeorm";

export class PosicionesPresupuestalesSapi1720311451601 implements MigrationInterface {
    name = 'PosicionesPresupuestalesSapi1720311451601'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "PPS_POSICIONES_PRESUPUESTARIAS_SAPI" ("PPS_CODIGO" SERIAL NOT NULL, "PPS_NUMERO" character varying(30) NOT NULL, "PPS_EJERCICIO" integer NOT NULL, "PPS_DESCRIPCION" character varying(500) NOT NULL, "PPS_CONSECUTIVO" character varying(3) NOT NULL, "PPS_ASIGNADO_A" character varying(40) NOT NULL, "PPS_ESTADO" boolean NOT NULL DEFAULT true, "PPS_USUARIO_CREACION" character varying(30), "PPS_FECHA_CREACION" TIMESTAMP, "PPS_USUARIO_ACTUALIZACION" character varying(30), "PPS_FECHA_ACTUALIZACION" TIMESTAMP, "FK_POS_PRE_ORIGIN" integer, CONSTRAINT "UQ_be207165fc06321feb4b89e1033" UNIQUE ("PPS_NUMERO"), CONSTRAINT "UQ_1e628650118a5b03411285a42e3" UNIQUE ("PPS_DESCRIPCION"), CONSTRAINT "PK_433b51984d0384fa86e9c28bf11" PRIMARY KEY ("PPS_CODIGO")); COMMENT ON COLUMN "PPS_POSICIONES_PRESUPUESTARIAS_SAPI"."PPS_CODIGO" IS 'Clave primaria de tabla'; COMMENT ON COLUMN "PPS_POSICIONES_PRESUPUESTARIAS_SAPI"."PPS_NUMERO" IS 'Número de posición presupuestal sapi'; COMMENT ON COLUMN "PPS_POSICIONES_PRESUPUESTARIAS_SAPI"."PPS_EJERCICIO" IS 'Ejercicio de aplicación de posición presupuestal sapi'; COMMENT ON COLUMN "PPS_POSICIONES_PRESUPUESTARIAS_SAPI"."PPS_DESCRIPCION" IS 'Descripción de la posición presupuestal sapi'; COMMENT ON COLUMN "PPS_POSICIONES_PRESUPUESTARIAS_SAPI"."PPS_CONSECUTIVO" IS 'Consecutivo de la posición presupuestal sapi'; COMMENT ON COLUMN "PPS_POSICIONES_PRESUPUESTARIAS_SAPI"."PPS_ASIGNADO_A" IS 'Asignado a de la posición presupuestal sapi'; COMMENT ON COLUMN "PPS_POSICIONES_PRESUPUESTARIAS_SAPI"."PPS_ESTADO" IS 'Estado lógico de eliminación de la posición presupuestal de origen'; COMMENT ON COLUMN "PPS_POSICIONES_PRESUPUESTARIAS_SAPI"."PPS_USUARIO_CREACION" IS 'Documento de usuario que creó'; COMMENT ON COLUMN "PPS_POSICIONES_PRESUPUESTARIAS_SAPI"."PPS_FECHA_CREACION" IS 'Fecha creación'; COMMENT ON COLUMN "PPS_POSICIONES_PRESUPUESTARIAS_SAPI"."PPS_USUARIO_ACTUALIZACION" IS 'Documento de usuario que actualizó'; COMMENT ON COLUMN "PPS_POSICIONES_PRESUPUESTARIAS_SAPI"."PPS_FECHA_ACTUALIZACION" IS 'Fecha actualización'; COMMENT ON COLUMN "PPS_POSICIONES_PRESUPUESTARIAS_SAPI"."FK_POS_PRE_ORIGIN" IS 'Clave primaria de tabla'`);
        await queryRunner.query(`ALTER TABLE "PPS_POSICIONES_PRESUPUESTARIAS_SAPI" ADD CONSTRAINT "FK_a4a66839d67ef6abfe881a8e5b3" FOREIGN KEY ("FK_POS_PRE_ORIGIN") REFERENCES "PPR_POSICIONES_PRESUPUESTARIAS_ORIGEN"("PPR_CODIGO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "PPS_POSICIONES_PRESUPUESTARIAS_SAPI" DROP CONSTRAINT "FK_a4a66839d67ef6abfe881a8e5b3"`);
        await queryRunner.query(`DROP TABLE "PPS_POSICIONES_PRESUPUESTARIAS_SAPI"`);
    }

}
