interface IPersons {
    id?: number;
    documentType: string;
    document: string;
    names: string;
    lastNames: string;
    gender: string;
    address: string;
    phone: string;
    email: string;
    birthDate: Date;
    bloodType: string;
    type: string;
    status: boolean;
    campus: number;
    createDocumentUserAt?: string;
    createDateAt?: Date;
    updateDocumentUserAt?: string;
    updateDateAt?: Date;
}

interface SeedData {
    persons: IPersons[];
}

export const initialDataPersons: SeedData = {
    persons: [
        {
            id: 1,
            documentType: "CC",
            document: "123456789",
            names: "Sebastian",
            lastNames: "Usuario Prueba",
            gender: "M",
            address: "Carrera 26A # 121 - 43",
            phone: "3129812187",
            email: "sebastianmedina.test@correo.com",
            birthDate: new Date("1995-05-02"),
            bloodType: "O+",
            type: "A1",
            status: true,
            campus: 1,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 2,
            documentType: "CC",
            document: "1216981213",
            names: "Fernanda",
            lastNames: "Barrera Ruiz",
            gender: "F",
            address: "Calle 46A # 12 - 432",
            phone: "3129812111",
            email: "fernandaruiz.test@correo.com",
            birthDate: new Date("1999-12-11"),
            bloodType: "A+",
            type: "A1",
            status: true,
            campus: 1,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 3,
            documentType: "CC",
            document: "1217182190",
            names: "Julian",
            lastNames: "Hinestroza Villada",
            gender: "M",
            address: "Carrera 26A # 121 - 32",
            phone: "3118941090",
            email: "julianhonestroza.test@correo.com",
            birthDate: new Date("2001-07-07"),
            bloodType: "B+",
            type: "A1",
            status: true,
            campus: 1,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 4,
            documentType: "CC",
            document: "12171092133",
            names: "Uriel",
            lastNames: "Castaño Carvajal",
            gender: "M",
            address: "Carrera 10A # 199 - 1C",
            phone: "3162519987",
            email: "urielcastano.test@correo.com",
            birthDate: new Date("1997-03-15"),
            bloodType: "B-",
            type: "A1",
            status: true,
            campus: 1,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 5,
            documentType: "CC",
            document: "98543109",
            names: "Carolina Antonia",
            lastNames: "Sanchez Upegui",
            gender: "F",
            address: "Carrera 26A # 121 - 43",
            phone: "3112129843",
            email: "carolinaantonia1.test@correo.com",
            birthDate: new Date("1989-09-21"),
            bloodType: "AB+",
            type: "A1",
            status: true,
            campus: 1,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 6,
            documentType: "CC",
            document: "1216717213",
            names: "Bartolomeo",
            lastNames: "Urrutia Yepes",
            gender: "M",
            address: "Carrera 12A # 381 - 121",
            phone: "3129032121",
            email: "bartourrutia.test@correo.com",
            birthDate: new Date("2001-11-30"),
            bloodType: "O+",
            type: "A1",
            status: true,
            campus: 2,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 7,
            documentType: "CC",
            document: "1190222012",
            names: "Gabriela",
            lastNames: "Carmona Avila",
            gender: "F",
            address: "Carrera 121 # 12 - 431",
            phone: "3102229124",
            email: "gabrielacarmonaa.test@correo.com",
            birthDate: new Date("1996-08-26"),
            bloodType: "O+",
            type: "A1",
            status: true,
            campus: 2,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 8,
            documentType: "CC",
            document: "121943328",
            names: "Jonhatan Alexis",
            lastNames: "Valenzuela Calle",
            gender: "M",
            address: "Carrera 15A # 32 - 149",
            phone: "3118921001",
            email: "eljohnatanalexis1.test@correo.com",
            birthDate: new Date("1995-09-21"),
            bloodType: "B+",
            type: "A1",
            status: true,
            campus: 2,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 9,
            documentType: "CC",
            document: "1216717949",
            names: "Juan Sebastian",
            lastNames: "Medina Toro",
            gender: "M",
            address: "Carrera 158 # 134 - 4232A",
            phone: "3117115833",
            email: "jsebastian19952011@gmail.com",
            birthDate: new Date("1995-05-02"),
            bloodType: "O+",
            type: "A1",
            status: true,
            campus: 3,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 10,
            documentType: "CC",
            document: "3356409",
            names: "Fabio de Jesus",
            lastNames: "Medina Henao",
            gender: "M",
            address: "Carrera 158 # 134 - 4232A",
            phone: "3136339136",
            email: "f.dejesus.medinahenao1957@gmail.com",
            birthDate: new Date("1957-01-02"),
            bloodType: "O+",
            type: "A1",
            status: true,
            campus: 3,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 11,
            documentType: "CC",
            document: "98543091",
            names: "Luis Daniel",
            lastNames: "Perea Domingues",
            gender: "M",
            address: "Calle 1290A # 218 - 323C",
            phone: "3109021893",
            email: "danielperea29o.test@correo.com",
            birthDate: new Date("1991-10-24"),
            bloodType: "A+",
            type: "A1",
            status: true,
            campus: 4,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 12,
            documentType: "CC",
            document: "43576326",
            names: "Monica Cecilia",
            lastNames: "Toro Toro",
            gender: "F",
            address: "Carrera 158 # 134 - 4232A",
            phone: "3053783193",
            email: "m.ceciliatoro1973@gmail.com",
            birthDate: new Date("1973-08-02"),
            bloodType: "O+",
            type: "A1",
            status: true,
            campus: 3,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 13,
            documentType: "CC",
            document: "1109222129",
            names: "Joel Arley",
            lastNames: "Patarrollo Loaiza",
            gender: "M",
            address: "Calle 329C # 218 - 12",
            phone: "3109201112",
            email: "parraolartejoeldejesus@gmail.com",
            birthDate: new Date("1998-03-15"),
            bloodType: "B-",
            type: "A1",
            status: true,
            campus: 3,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 14,
            documentType: "CC",
            document: "1218999201",
            names: "Lorena Carolina",
            lastNames: "Quintero Cano",
            gender: "F",
            address: "Calle 16A43 # 1892 - 321",
            phone: "3109021112",
            email: "lorenacarolina234.test@correo.com",
            birthDate: new Date("1999-09-10"),
            bloodType: "AB+",
            type: "A1",
            status: true,
            campus: 1,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 15,
            documentType: "CC",
            document: "1219222012",
            names: "Geraldine",
            lastNames: "Batistuta Barragan",
            gender: "F",
            address: "Calle 589A # 54 - 10093",
            phone: "3128920012",
            email: "lageraldinbati4.test@correo.com",
            birthDate: new Date("1999-09-10"),
            bloodType: "AB-",
            type: "A1",
            status: true,
            campus: 5,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 16,
            documentType: "CC",
            document: "895401211",
            names: "Luz Elena",
            lastNames: "Gaviria Urrutia",
            gender: "F",
            address: "Carrera 312C # 493A - 594B",
            phone: "3002901192",
            email: "luzelenalagab.test@correo.com",
            birthDate: new Date("1985-07-15"),
            bloodType: "A-",
            type: "A1",
            status: true,
            campus: 5,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 17,
            documentType: "CC",
            document: "1000921021",
            names: "Yordan Arley",
            lastNames: "Bedoya Tobar",
            gender: "M",
            address: "Calle 54A # 412C - 1092",
            phone: "3102199921",
            email: "yordanbedoya545.test@correo.com",
            birthDate: new Date("2001-10-10"),
            bloodType: "O-",
            type: "A1",
            status: true,
            campus: 3,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 18,
            documentType: "CC",
            document: "1219000212",
            names: "Carolina",
            lastNames: "Hinestroza Gallan",
            gender: "F",
            address: "Carrera 54A # 54 - 3133C",
            phone: "3039220021",
            email: "carohinestro4.test@correo.com",
            birthDate: new Date("1997-04-12"),
            bloodType: "O+",
            type: "A1",
            status: true,
            campus: 1,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 19,
            documentType: "CC",
            document: "879053812",
            names: "Veronica",
            lastNames: "Perez Torres",
            gender: "F",
            address: "Carrera 548A # 902 - 543A",
            phone: "3167281192",
            email: "veronicaperez43.test@correo.com",
            birthDate: new Date("1987-12-30"),
            bloodType: "O+",
            type: "A1",
            status: true,
            campus: 1,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 20,
            documentType: "CC",
            document: "1217888291",
            names: "Jorge Ivan",
            lastNames: "Toro Toro",
            gender: "M",
            address: "Calle 145A # 4899 - 231C",
            phone: "3129012221",
            email: "jorgetoro32.test@correo.com",
            birthDate: new Date("1998-10-11"),
            bloodType: "A+",
            type: "A1",
            status: true,
            campus: 1,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        },
        {
            id: 21,
            documentType: "CC",
            document: "1902111213",
            names: "Helena",
            lastNames: "Diaz Castañeda",
            gender: "F",
            address: "Carrera 54A # 490 - 4312C",
            phone: "3129392211",
            email: "helenadiaz43.test@correo.com",
            birthDate: new Date("1998-10-11"),
            bloodType: "B-",
            type: "A1",
            status: true,
            campus: 1,
            createDocumentUserAt: "123456789",
            createDateAt: new Date(),
            updateDocumentUserAt: "123456789",
            updateDateAt: new Date()
        }
    ]
}